### ISSUE TITLE
Fatal error while activating plugin

### ISSUE THREAD

**Issue by lmartins** [WebDevStudios/WDS-Custom-Login-Page#1]
When I try to activate the plugin I get:

> Plugin could not be activated because it triggered a fatal error.
> Warning: require_once(/var/www/html/wp-content/plugins/WDS-Custom-Login-Page//inc/cmb2/init.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/WDS-Custom-Login-Page/wds-custom-login-page.php on line 35

Btw, why does the plugin require CMB2 as a dependency, isn't this for front-end login page only?

**Comment by jazzsequence** [comment]
CMB2 is used for the options page. 

Unfortunately, CMB2 is added as a submodule in this repository and those don't get carried over to the zip file when you download the zip. The workaround, for now (until I fix the repo and remove CMB2 as a submodule) is to download cmb2 separately, and add it to a `/inc/cmb2` directory in the plugin.

**Comment by jazzsequence** [comment]
Or you can git clone the repo. :)

**Comment by jtsternberg** [comment]
git clone --recursive. ;)

**Comment by lmartins** [comment]
Cool, thank you both @jazzsequence @jtsternberg 
Feeling the pressure to move to CMB2, still no quite convinced about it's UI though... :(

Other than that, I would just jump right in, but you know us designers, we are pretty picky about those things, and you may or may not agree there's some polishing needed. But that's off topic, thanks again for the clarification on the error.

**Comment by lmartins** [comment]
Btw, I was just testing this again. This time having CMB2 installed on my site before trying to activate WDS-Custom-Login.

The plugin still fails, trying to load the bundled CMB2 version. Shouldn't it check to see if CMB2 were already available, avoiding in this case loading the bundled version?

Thanks.

**Comment by jtsternberg** [comment]
You'll still want to `git clone --recursive git@github.com:WebDevStudios/WDS-Custom-Login-Page.git` to get this library. That will pull down the library and any dependencies. CMB2 is unique in that it handles doing the is-CMB2-available checking internally, so there is no need to to conditionally load it. So that being said, the CMB2 file it's trying to load should still be there.

**Comment by jazzsequence** [comment]
Created a new ticket to solve this (#9 see above). This will eliminate the requirement for `git clone --recursive` and solve any potential WP.org repository inclusion issues down the line. Closing this ticket out.
